CREATE DATABASE [ChatDB]
GO

USE [ChatDB]
GO

CREATE TABLE [Users]
(
Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
[Username] NVARCHAR(128) NOT NULL UNIQUE CHECK([Username] <> ''),
[Password] NVARCHAR(64) NOT NULL CHECK([Password] <> ''),
[AccountCreationTime] DATETIME NOT NULL DEFAULT GETDATE(),
[IsAdmin] BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE [Chats]
(
Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
[Name] NVARCHAR(128) NOT NULL,
[CreationTime] DATETIME NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE [Messages]
(
Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
[UserId] INT NOT NULL,
FOREIGN KEY ([UserId]) REFERENCES [Users](Id),
[ChatId] INT NOT NULL,
FOREIGN KEY ([ChatId]) REFERENCES [Chats](Id),
[SendTime] DATETIME NOT NULL DEFAULT GETDATE(),
[Text] NVARCHAR(MAX) NOT NULL
);
GO

CREATE TABLE [Logs]
(
Id INT PRIMARY KEY NOT NULL IDENTITY(1, 1),
[UserId] INT NOT NULL,
FOREIGN KEY ([UserId]) REFERENCES [Users](Id),
[ConnectionTime] NVARCHAR(MAX) NOT NULL,
[DisconnectionTime] NVARCHAR(MAX)
);
GO

INSERT INTO [Users] ([Username], [Password], [IsAdmin])
VALUES
('admin', 'admin123', 1),
('Bob', 'bobby331', 0),
('JakeBoss', 'qwerty000', 0)
GO

INSERT INTO [Chats] ([Name])
VALUES
('General'),
('Memes'),
('News')
GO